#
# Module manifest for module 'Diag-V'
#
# Generated by: Jake Morrison
#
# Generated on: 12/10/2017
#

@{
    
    # Script module or binary module file associated with this manifest
    RootModule = 'Diag-V.psm1'
    
    # Version number of this module.
    ModuleVersion = '1.0'
    
    # ID used to uniquely identify this module
    GUID = 'd0a9150d-b6a4-4b17-a325-e3a24fed0aa9'
    
    # Author of this module
    Author = 'Jake Morrison'
    
    # Company or vendor of this module
    CompanyName = 'Tech Thoughts'
    
    # Copyright statement for this module
    Copyright = '(c) 2017-2018 Jacob Morrison. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'A Hyper-V Diagnostic Utility'
    
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '4.0'
    
    # Functions to export from this module
    FunctionsToExport = @(
        'Get-VMStatus',
        'Get-VMInfo',
        'Get-VMReplicationStatus',
        'Get-VMLocationPathInfo',
        'Get-IntegrationServicesCheck',
        'Get-BINSpaceInfo',
        'Get-VMAllVHDs',
        'Get-SharedVHDs',
        'Test-HyperVAllocation',
        'Get-CSVtoPhysicalDiskMapping',
        'Get-FileSizes',
        'Get-HyperVLogs',
        'Show-DiagVMenu'
    )
    
    #Specifies the URL of a web page about this project.
    #ProjectUri = 'https://github.com/techthoughts2/Diag-V'
        
    }